spring.application.name=ida
# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (POSTGRESQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/idadb
spring.datasource.username=joss
spring.datasource.password=1997
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
# 'validate' comprueba que las tablas coincidan con las entidades, pero no las crea.
# Es la opción más segura cuando se usa Flyway.
spring.jpa.hibernate.ddl-auto=validate

# Muestra el SQL que Hibernate genera. Útil para depurar.
spring.jpa.show-sql=true

# Formatea el SQL mostrado en la consola para que sea más legible.
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONFIGURACIÓN DE FLYWAY
# ===================================================================
spring.flyway.baseline-on-migrate=true
# ===================================================================

# =======================================================
# CONFIGURACIÓN DE SEGURIDAD JWT (v2.0 - Refresh Tokens)
# =======================================================
# TU CLAVE SECRETA VA AQUÍ (La que ya tienes)
#application.security.jwt.secret-key=HPRtfCOv4su5M0LclmjfqGciz0UMtVX97MFvbRtvnmqVQ0dFEDr6z6el26UkSmCPOzcCiUEZFmG+p6u6jrqlaw==

# Expiración del Token de Acceso (Access Token): 15 minutos (900,000 ms)
#application.security.jwt.access-expiration=900000

# Expiración del Token de Refresco (Refresh Token): 30 días (2,592,000,000 ms)
#application.security.jwt.refresh-expiration=2592000000

# === JWT configuration ===
jwt.secret=5Vc89m0bsDOEETBqqnKsXJ66/78JJ5KT2YHj2wxM7pwztuNLNvn1Mo2usiyekPHQN/NgQE/Py5zgUS6q6qDK1w==
jwt.access.expiration-ms=900000
jwt.refresh.expiration-ms=604800000
# LOGGING DE DEBUG PARA SPRING SECURITY
# ===================================================================
logging.level.org.springframework.security=DEBUG